-- Sokilé v34 — annuaire et demandes publicitaires
-- À exécuter une fois dans Supabase > SQL Editor avant de déployer l'interface v34.
-- Le script est idempotent : il peut être relancé sans dupliquer les tables.

begin;

create or replace function public.sokile_is_admin()
returns boolean
language sql
stable
security definer
set search_path=public
as $$
  select coalesce(auth.jwt()->>'email','') = 'contact@sokile.com'
$$;
revoke all on function public.sokile_is_admin() from public;
grant execute on function public.sokile_is_admin() to authenticated;

create table if not exists public.professionals (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  business_name text not null,
  specialty text not null,
  countries text[] not null default '{}',
  zones text,
  email text not null,
  phone text,
  website text,
  pricing text,
  description text,
  verification_reference text,
  consent_at timestamptz,
  status text not null default 'en_attente'
    check(status in('en_attente','validee','refusee','modifications_demandees')),
  active boolean not null default false,
  moderation_note text
);
alter table public.professionals add column if not exists verification_reference text;
alter table public.professionals add column if not exists consent_at timestamptz;
create index if not exists professionals_owner_idx on public.professionals(owner_id);
create index if not exists professionals_status_idx on public.professionals(status,created_at desc);

create table if not exists public.advertising_requests (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  contact_name text not null,
  company text,
  email text not null,
  phone text,
  format text not null,
  objective text,
  target_countries text[] not null default '{}',
  budget text,
  desired_period text,
  destination_url text,
  message text,
  consent_at timestamptz,
  status text not null default 'en_attente'
    check(status in('en_attente','en_cours','acceptee','refusee','modifications_demandees')),
  moderation_note text
);
alter table public.advertising_requests add column if not exists objective text;
alter table public.advertising_requests add column if not exists consent_at timestamptz;
create index if not exists advertising_owner_idx on public.advertising_requests(owner_id);
create index if not exists advertising_status_idx on public.advertising_requests(status,created_at desc);

-- Un utilisateur ne peut ni s'auto-valider ni rendre sa fiche publique.
-- Le compte administrateur conserve, lui, les valeurs de modération choisies.
create or replace function public.sokile_request_workflow()
returns trigger
language plpgsql
security invoker
set search_path=public
as $$
begin
  if auth.role()='authenticated' and not public.sokile_is_admin() then
    if tg_op='INSERT' then
      new.owner_id:=auth.uid();
    else
      new.owner_id:=old.owner_id;
    end if;
    new.status:='en_attente';
    new.moderation_note:=null;
    if tg_table_name='professionals' then new.active:=false; end if;
  elsif tg_op='INSERT' and new.owner_id is null then
    new.owner_id:=auth.uid();
  end if;
  new.updated_at:=now();
  return new;
end $$;

drop trigger if exists sokile_professional_workflow on public.professionals;
create trigger sokile_professional_workflow before insert or update on public.professionals
for each row execute function public.sokile_request_workflow();
drop trigger if exists sokile_advertising_workflow on public.advertising_requests;
create trigger sokile_advertising_workflow before insert or update on public.advertising_requests
for each row execute function public.sokile_request_workflow();

alter table public.professionals enable row level security;
alter table public.advertising_requests enable row level security;

do $$ declare t text; p record; begin
  foreach t in array array['professionals','advertising_requests'] loop
    for p in select policyname from pg_policies where schemaname='public' and tablename=t loop
      execute format('drop policy if exists %I on public.%I',p.policyname,t);
    end loop;
    execute format('create policy %I on public.%I for select to authenticated using(owner_id=auth.uid() or public.sokile_is_admin())','sokile_read_'||t,t);
    execute format('create policy %I on public.%I for insert to authenticated with check(owner_id=auth.uid() or public.sokile_is_admin())','sokile_insert_'||t,t);
    execute format('create policy %I on public.%I for update to authenticated using(owner_id=auth.uid() or public.sokile_is_admin()) with check(owner_id=auth.uid() or public.sokile_is_admin())','sokile_update_'||t,t);
    execute format('create policy %I on public.%I for delete to authenticated using(public.sokile_is_admin())','sokile_delete_'||t,t);
    execute format('grant select,insert,update,delete on public.%I to authenticated',t);
    execute format('revoke all on public.%I from anon',t);
  end loop;
end $$;

create or replace view public.public_professionals as
select id,business_name,specialty,countries,zones,phone,website,pricing,description
from public.professionals
where active=true and status='validee';
revoke all on public.public_professionals from public;
grant select on public.public_professionals to anon,authenticated;

commit;

-- Contrôle : doit retourner trois nombres sans erreur.
select
  (select count(*) from public.professionals where status='en_attente') as prestataires_a_valider,
  (select count(*) from public.professionals where active=true and status='validee') as prestataires_publics,
  (select count(*) from public.advertising_requests where status='en_attente') as publicites_a_traiter;
