-- Sokilé v33 — annonces modifiables, annuaire, publicité et modération
-- Supabase > SQL Editor > New query > coller ce fichier > Run
begin;

alter table public.properties add column if not exists owner_id uuid references auth.users(id) on delete set null;
alter table public.properties add column if not exists updated_at timestamptz not null default now();
alter table public.properties add column if not exists submitted_at timestamptz not null default now();
create index if not exists properties_owner_id_idx on public.properties(owner_id);

-- Une modification par le propriétaire retire immédiatement l'annonce publique
-- et la remet dans la file de validation. Le rôle service/admin reste libre de modérer.
create or replace function public.sokile_property_workflow()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  if auth.role()='authenticated' then
    if tg_op='INSERT' then
      new.owner_id:=auth.uid();
    else
      new.owner_id:=old.owner_id;
    end if;
    new.status:='en_attente';
    new.active:=false;
    new.verified:=false;
    new.validated_at:=null;
    new.moderation_note:=null;
    new.submitted_at:=now();
  end if;
  new.updated_at:=now();
  return new;
end $$;
drop trigger if exists sokile_protect_property_moderation on public.properties;
drop trigger if exists sokile_property_workflow on public.properties;
create trigger sokile_property_workflow before insert or update on public.properties
for each row execute function public.sokile_property_workflow();

alter table public.properties enable row level security;
drop policy if exists "sokile_owner_read_properties" on public.properties;
drop policy if exists "sokile_owner_insert_properties" on public.properties;
drop policy if exists "sokile_owner_update_properties" on public.properties;
drop policy if exists "sokile_owner_delete_properties" on public.properties;
create policy "sokile_owner_read_properties" on public.properties for select to authenticated using(owner_id=auth.uid());
create policy "sokile_owner_insert_properties" on public.properties for insert to authenticated with check(owner_id=auth.uid() and status='en_attente' and active=false and verified=false);
create policy "sokile_owner_update_properties" on public.properties for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid());
create policy "sokile_owner_delete_properties" on public.properties for delete to authenticated using(owner_id=auth.uid());
grant select,insert,update,delete on public.properties to authenticated;
revoke all on public.properties from anon;

create or replace view public.public_properties as
select id,created_at,title,type,country,city,neighborhood,price,price_eur,surface,rooms,bathrooms,
verified,agent_name,tags,description,advertiser_type,agency_name,user_name,user_phone,photos
from public.properties where active=true and status='validee';
revoke all on public.public_properties from public;
grant select on public.public_properties to anon,authenticated;

create table if not exists public.professionals (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  business_name text not null, specialty text not null, countries text[] not null default '{}', zones text,
  email text not null, phone text, website text, pricing text, description text,
  status text not null default 'en_attente' check(status in('en_attente','validee','refusee','modifications_demandees')),
  active boolean not null default false, moderation_note text
);
create index if not exists professionals_owner_idx on public.professionals(owner_id);

create table if not exists public.advertising_requests (
  id bigint generated by default as identity primary key,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  contact_name text not null, company text, email text not null, phone text, format text not null,
  target_countries text[] not null default '{}', budget text, desired_period text, destination_url text, message text,
  status text not null default 'en_attente' check(status in('en_attente','en_cours','acceptee','refusee','modifications_demandees')),
  moderation_note text
);
create index if not exists advertising_owner_idx on public.advertising_requests(owner_id);

create or replace function public.sokile_request_workflow()
returns trigger language plpgsql security invoker set search_path=public as $$
begin
  if auth.role()='authenticated' then
    if tg_op='INSERT' then new.owner_id:=auth.uid(); else new.owner_id:=old.owner_id; end if;
    new.status:='en_attente'; new.moderation_note:=null;
    if tg_table_name='professionals' then new.active:=false; end if;
  end if;
  new.updated_at:=now(); return new;
end $$;
drop trigger if exists sokile_professional_workflow on public.professionals;
create trigger sokile_professional_workflow before insert or update on public.professionals for each row execute function public.sokile_request_workflow();
drop trigger if exists sokile_advertising_workflow on public.advertising_requests;
create trigger sokile_advertising_workflow before insert or update on public.advertising_requests for each row execute function public.sokile_request_workflow();

alter table public.professionals enable row level security;
alter table public.advertising_requests enable row level security;
do $$ declare t text; p record; begin
  foreach t in array array['professionals','advertising_requests'] loop
    for p in select policyname from pg_policies where schemaname='public' and tablename=t loop
      execute format('drop policy if exists %I on public.%I',p.policyname,t);
    end loop;
    execute format('create policy %I on public.%I for select to authenticated using(owner_id=auth.uid())','sokile_owner_read_'||t,t);
    execute format('create policy %I on public.%I for insert to authenticated with check(owner_id=auth.uid())','sokile_owner_insert_'||t,t);
    execute format('create policy %I on public.%I for update to authenticated using(owner_id=auth.uid()) with check(owner_id=auth.uid())','sokile_owner_update_'||t,t);
    execute format('grant select,insert,update on public.%I to authenticated',t);
    execute format('revoke all on public.%I from anon',t);
  end loop;
end $$;

create or replace view public.public_professionals as
select id,business_name,specialty,countries,zones,phone,website,pricing,description
from public.professionals where active=true and status='validee';
revoke all on public.public_professionals from public;
grant select on public.public_professionals to anon,authenticated;

commit;

-- Contrôle : ces nombres doivent s'afficher sans erreur.
select
  (select count(*) from public.properties where status='en_attente') as annonces_a_valider,
  (select count(*) from public.professionals where status='en_attente') as prestataires_a_valider,
  (select count(*) from public.advertising_requests where status='en_attente') as publicites_a_traiter;
