import test from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('../public/sokile-analytics.js',import.meta.url),'utf8');
function setup({saved=null,host='www.sokile.com',search='',broken=false}={}) {
 const storage=new Map(saved?[['sokile.analytics-consent.v1',saved]]:[]), scripts=[], nodes=[], listeners={}, writes=[];
 function element(tag){const handlers={},children={};return {tag,hidden:false,isConnected:true,setAttribute(){},addEventListener(n,f){handlers[n]=f;},click(){handlers.click?.({});},focus(){},querySelector(selector){return children[selector] ||= element('button');}};}
 const doc={readyState:'complete',referrer:'https://www.facebook.com/group?email=secret@example.com',activeElement:null,head:{appendChild(n){nodes.push(n);if(n.tag==='script')scripts.push(n);}},body:{appendChild(n){nodes.push(n);}},createElement:element,addEventListener(n,f){listeners['doc:'+n]=f;}};
 Object.defineProperty(doc,'cookie',{get(){return '_ga=old; _ga_ES3GX7T680=old; session=keep';},set(v){writes.push(v);}});
 let reloads=0;
 const win={setInterval(){},location:{hostname:host,pathname:'/',search,reload(){reloads++;}},localStorage:{getItem(k){if(broken)throw Error();return storage.get(k)||null;},setItem(k,v){if(broken)throw Error();storage.set(k,v);}},addEventListener(n,f){listeners[n]=f;}};
 vm.runInNewContext(source,{window:win,document:doc,URL,URLSearchParams,Date,Set,Number,JSON});
 const banner=nodes.find(x=>x.id==='sokile-consent');
 return {win,doc,scripts,nodes,banner,storage,writes,listeners,get reloads(){return reloads;},accept(){banner.querySelector('[data-choice="yes"]').click();},refuse(){banner.querySelector('[data-choice="no"]').click();},calls(){return (win.dataLayer||[]).map(x=>Array.from(x));}};
}
test('no Google script or queued event before a choice, including page and form events',()=>{const x=setup();x.win.sokileAnalytics.page('accueil');x.win.sokileAnalytics.event('listing_submit');assert.equal(x.scripts.length,0);assert.equal(x.calls().length,0);assert.equal(x.banner.hidden,false);});
test('refusal persists and never loads Google',()=>{const x=setup();x.refuse();x.win.sokileAnalytics.page('biens');assert.equal(x.scripts.length,0);const saved=x.storage.get('sokile.analytics-consent.v1');assert.equal(JSON.parse(saved).accepted,false);const y=setup({saved});assert.equal(y.banner.hidden,true);assert.equal(y.scripts.length,0);});
test('acceptance loads once, deduplicates page rendering and allows only known events',()=>{const x=setup();x.win.sokileAnalytics.page('biens');x.accept();x.win.sokileAnalytics.page('biens');x.win.sokileAnalytics.event('listing_submit',{email:'secret@example.com'});x.win.sokileAnalytics.event('secret@example.com');assert.equal(x.scripts.length,1);assert.equal(x.calls().filter(c=>c[1]==='page_view').length,1);assert.equal(x.calls().filter(c=>c[1]==='listing_submit').length,1);assert.ok(!JSON.stringify(x.calls()).includes('secret@example.com'));const config=x.calls().find(c=>c[0]==='config')[2];assert.equal(config.send_page_view,false);assert.equal(config.allow_google_signals,false);assert.equal(config.cookie_update,false);});
test('URL queries, fragments and referrer paths are not sent; valid campaign slugs survive',()=>{const x=setup({search:'?email=secret@example.com&access_token=abc&utm_source=facebook&utm_medium=social&utm_campaign=lancement-2026'});x.win.sokileAnalytics.page('accueil');x.accept();const c=x.calls().find(c=>c[0]==='config')[2];assert.equal(c.campaign_source,'facebook');assert.equal(c.campaign_name,'lancement-2026');assert.equal(c.page_location,'https://www.sokile.com/');assert.equal(c.page_referrer,'https://www.facebook.com');assert.ok(!JSON.stringify(x.calls()).includes('secret'));});
test('withdrawal disables Google before reloading, removes only GA cookies and stores refusal',()=>{const x=setup();x.win.sokileAnalytics.page('biens');x.accept();x.win.sokileAnalytics.preferences();x.refuse();assert.equal(x.win['ga-disable-G-ES3GX7T680'],true);assert.equal(x.reloads,1);assert.ok(x.writes.length>0);assert.ok(x.writes.every(v=>v.startsWith('_ga')));const before=x.calls().length;x.win.sokileAnalytics.event('listing_submit');assert.equal(x.calls().length,before);});
test('expired, future and malformed stored consent cannot enable tracking',()=>{for(const saved of ['broken',JSON.stringify({version:1,accepted:true,at:Date.now()-181*86400000}),JSON.stringify({version:1,accepted:true,at:Date.now()+86400000}),JSON.stringify({version:1,accepted:'yes',at:Date.now()})]){const x=setup({saved});x.win.sokileAnalytics.page('biens');assert.equal(x.scripts.length,0);assert.equal(x.banner.hidden,false);}});
test('storage failures leave site functional and do not imply consent',()=>{const x=setup({broken:true});x.win.sokileAnalytics.page('biens');assert.equal(x.scripts.length,0);assert.doesNotThrow(()=>x.refuse());});
test('preview hosts never send to the production property, even after acceptance',()=>{const x=setup({host:'preview.vercel.app'});x.win.sokileAnalytics.page('biens');x.accept();x.win.sokileAnalytics.event('listing_submit');assert.equal(x.scripts.length,0);assert.equal(x.calls().length,0);});
test('another tab withdrawing consent immediately disables this tab',()=>{const x=setup();x.win.sokileAnalytics.page('biens');x.accept();x.storage.set('sokile.analytics-consent.v1',JSON.stringify({version:1,accepted:false,at:Date.now()}));x.listeners.storage({key:'sokile.analytics-consent.v1'});assert.equal(x.win['ga-disable-G-ES3GX7T680'],true);assert.equal(x.reloads,1);});

test('different listing pages are counted while their identifiers stay private',()=>{const x=setup();x.accept();x.win.sokileAnalytics.page('annonce','123');x.win.sokileAnalytics.page('annonce','123');x.win.sokileAnalytics.page('annonce','456');assert.equal(x.calls().filter(c=>c[1]==='page_view').length,2);assert.ok(!JSON.stringify(x.calls()).includes('456'));});
