import test from 'node:test';import assert from 'node:assert/strict';
import {safeProgramUrl,programState,programDelivery,inventoryStale,validateProgram} from '../src/programs.mjs';
import {buildDecisionMessage} from '../supabase/functions/notify-admin/moderation.mjs';
import {createNotificationHandler} from '../supabase/functions/notify-admin/handler.mjs';
test('documents et liens externes interdisent les protocoles dangereux',()=>{for(const u of ['javascript:alert(1)','data:text/html,test','http://example.test','https://user:password@example.test'])assert.equal(safeProgramUrl(u),'');assert.equal(safeProgramUrl('https://example.test/plan.pdf'),'https://example.test/plan.pdf');});
test('avancement, disponibilité et échéance sont distincts',()=>{assert.equal(programState({status:'validee',expires_at:'2025-01-01'}),'Expiré');assert.equal(programDelivery({stage:'livre'}),'Programme livré');assert.match(programDelivery({stage:'construction',delivery_quarter:4,delivery_year:2027}),/prévisionnelle/);assert.equal(inventoryStale({inventory_updated_at:'2026-01-01'},Date.parse('2026-04-02')),true);});
test('le refus du programme reprend le message personnalisé et la validation précise un an',()=>{const base={id:'p',title:'Résidence',email:'contact@example.test',status:'refusee',moderation_note:'Merci de préciser la date prévisionnelle de livraison avant publication.'};assert.match(buildDecisionMessage('development_programs',base).text,/date prévisionnelle/);const text=buildDecisionMessage('development_programs',{...base,status:'validee',expires_at:'2027-09-23'}).text;assert.match(text,/1 an/);assert.match(text,/23\/09\/2027/);assert.doesNotMatch(text,/avant publication/);});
test('un contact neuf notifie le promoteur vérifié et la gestion, une seule fois si même adresse',async()=>{let mail;const handle=createNotificationHandler({env:k=>({WEBHOOK_SECRET:'test',RESEND_API_KEY:'test'})[k],send:async(url,o)=>{mail=JSON.parse(o.body);return new Response(JSON.stringify({id:'sent'}));}});const r=await handle(new Request('https://example.test',{method:'POST',headers:{'x-webhook-secret':'test'},body:JSON.stringify({type:'INSERT',table:'program_inquiries',record:{id:'p',recipient_email:'contact@sokile.com',contact_name:'Test',email:'client@example.test',message:'Informations',title:'Résidence'}})}));assert.equal(r.status,200);assert.deepEqual(mail.to,['contact@sokile.com']);assert.match(mail.text,/client@example.test/);});
test('un rappel de programme exige l’authentification et un destinataire valide',async()=>{let calls=0;const h=createNotificationHandler({env:k=>({WEBHOOK_SECRET:'test',RESEND_API_KEY:'test'})[k],send:async()=>{calls++;return new Response(JSON.stringify({id:'sent'}));}});const payload={type:'REMINDER',table:'development_programs',record:{id:'p',email:'bad\nemail'}};const r=await h(new Request('https://example.test',{method:'POST',headers:{'x-webhook-secret':'test'},body:JSON.stringify(payload)}));assert.equal(r.status,422);assert.equal(calls,0);});
