import {useEffect,useState} from 'react';
import {needsTitleReview} from './directory-review.mjs';
export function DirectoryProof({api,user,documents,onChange,disabled,onBusy}) {
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[previous,setPrevious]=useState([]),[reuseOpen,setReuseOpen]=useState(false);
 const upload=async(code,file)=>{if(!file)return;setBusy(true);onBusy?.(true);setError('');try{onChange({...documents,[code]:await api.upload(user,file)});}catch(e){setError(e.message);}finally{setBusy(false);onBusy?.(false);}};
 const reuse=async()=>{setError('');setBusy(true);onBusy?.(true);try{const choices=await api.reusable(user);setPrevious(choices);setReuseOpen(true);}catch(e){setError(e.message);}finally{setBusy(false);onBusy?.(false);}};
 return <fieldset disabled={disabled||busy} className="pv-document directory-proof"><legend>Votre justificatif professionnel *</legend><p>Une photo lisible ou un PDF : immatriculation, inscription à un ordre ou autre document officiel adapté à votre activité. Une seule pièce de base pour cette fiche, même si vous intervenez dans plusieurs pays.</p><label>Ajouter le justificatif · PDF, JPG ou PNG · 5 Mo maximum<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{upload('registration',e.target.files?.[0]);e.target.value='';}}/></label>{documents.registration?.path&&<p className="pv-file">Pièce jointe : {documents.registration.name||'Justificatif professionnel'}</p>}<button type="button" className="directory-secondary" onClick={reuse}>Réutiliser une pièce déjà déposée</button>{reuseOpen&&(previous.length?<label>Choisir une pièce<select defaultValue="" onChange={e=>{if(e.target.value==='')return;const item=previous[Number(e.target.value)];if(item)onChange({...documents,registration:{path:item.path,name:item.name}});}}><option value="">Choisir…</option>{previous.map((item,i)=><option key={item.path} value={i}>{item.label}</option>)}</select></label>:<p>Aucune pièce de base enregistrée dans votre compte.</p>)}<details><summary>Ajouter un complément si nécessaire</summary><p>Ajoutez une habilitation ou un mandat seulement si votre première pièce ne suffit pas. Aucun passeport ni relevé bancaire n’est demandé.</p>{[['authority','Habilitation ou référence professionnelle'],['mandate','Mandat pour représenter la structure']].map(([code,label])=><label key={code}>{label}<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{upload(code,e.target.files?.[0]);e.target.value='';}}/>{documents[code]?.path&&<span>{documents[code].name||'Fichier ajouté'} <button type="button" className="directory-secondary" onClick={()=>{const next={...documents};delete next[code];onChange(next);}}>Retirer</button></span>}</label>)}</details><p className="pv-small">Ces fichiers restent privés. Gardez les mentions utiles lisibles et masquez les données personnelles sans rapport avec le contrôle.</p>{error&&<p className="pv-error" role="alert">{error}</p>}</fieldset>;
}
export function DirectoryReview({record,user,api,value,onChange,disabled}) {
 const [fileUrl,setFileUrl]=useState(''),[error,setError]=useState('');
 useEffect(()=>()=>{if(fileUrl)URL.revokeObjectURL(fileUrl);},[fileUrl]);
 const set=(k,v)=>onChange({...value,[k]:v});
 return <fieldset disabled={disabled} className="pv-document directory-proof"><legend>Contrôle de la fiche annuaire</legend><p>Examinez les pièces et la cohérence de la fiche. Aucun appel systématique ni certification d’authenticité n’est attendu. En cas de doute non résolu, demandez un complément.</p>{Object.entries(record.directory_documents||{}).map(([code,d])=><p key={code}><button type="button" className="directory-secondary" onClick={async()=>{setError('');setFileUrl('');try{setFileUrl(await api.open(user,d.path));}catch(e){setError(e.message);}}}>Ouvrir : {d.name||code}</button></p>)}{!record.directory_documents?.registration?.path&&<p className="pv-error">Justificatif de base manquant. Demandez au professionnel de compléter sa fiche.</p>}{fileUrl&&<a href={fileUrl} target="_blank" rel="noopener noreferrer">Voir le document privé</a>}{[['identity','Le justificatif est lisible ; nom, activité et représentation concordent. Les dates ont été examinées.'],['content','Les coordonnées, la présentation et les pays annoncés sont cohérents ; aucune promesse trompeuse repérée.']].map(([k,label])=><label className="pv-check" key={k}><input type="checkbox" checked={!!value[k]} onChange={e=>set(k,e.target.checked)}/>{label}</label>)}<label>Titre ou habilitation revendiqués<select value={value.title||''} onChange={e=>set('title',e.target.value)}><option value="">Choisir le résultat du contrôle…</option><option value="checked">Référence recoupée avec une source indépendante</option>{!needsTitleReview(record.specialty)&&<option value="not_applicable">Aucun titre ni acte réglementé revendiqué dans cette fiche</option>}</select></label><p className="pv-small">Pour {record.countries?.join(', ')} : si un titre ou un acte réglementé est revendiqué, consignez le registre officiel ou la confirmation obtenue, sa date et le résultat. Une simple déclaration ne suffit pas. Si le périmètre reste incertain, laissez la fiche à compléter.</p><label>Note privée du contrôle<textarea rows={3} maxLength={4000} value={value.notes||''} onChange={e=>set('notes',e.target.value)} placeholder="Pièce examinée, concordance du nom et de l’activité ; si nécessaire, source indépendante, pays concernés et résultat."/></label><label>Échéance du contrôle<input type="date" value={value.until||''} onChange={e=>set('until',e.target.value)}/></label><p className="pv-small">Au plus tard dans douze mois, et plus tôt si une pièce comporte une échéance.</p>{error&&<p className="pv-error">{error}</p>}</fieldset>;
}
