import {useState,useEffect} from 'react';
import {individualNeeds,individualError} from './individual-verification.mjs';
export function IndividualPanel({api,user,property,admin=false}){
 const [record,setRecord]=useState(null),[loaded,setLoaded]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[editing,setEditing]=useState(false),[tick,setTick]=useState(0),[fileUrl,setFileUrl]=useState('');
 const [f,setF]=useState({holder_name:'',basis:'',situation:'sole',documents:{},consent:false});
 const [checks,setChecks]=useState({}),[evidence,setEvidence]=useState(''),[response,setResponse]=useState(''),[until,setUntil]=useState(new Date(Date.now()+180*86400000).toISOString().slice(0,10));
 const role=property.details?.advertiser_role,needs=individualNeeds(role);
 useEffect(()=>{let active=true;setLoaded(false);api.load(user,property.id).then(rows=>{if(!active)return;const d=rows[0];setRecord(d||null);if(d)setF({...d,consent:false});setLoaded(true);}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[property.id,user.token,tick]);
 useEffect(()=>()=>{if(fileUrl)URL.revokeObjectURL(fileUrl);},[fileUrl]);
 const put=(k,v)=>setF(old=>({...old,[k]:v}));const putDoc=(k,v)=>setF(old=>({...old,documents:{...old.documents,[k]:{...old.documents[k],...v}}}));
 const upload=async(k,file)=>{if(!file)return;setBusy(true);setError('');try{putDoc(k,await api.upload(user,file));}catch(e){setError(e.message);}finally{setBusy(false);}};
 const save=async()=>{const invalid=individualError(f,role);if(invalid){setError(invalid);return;}setBusy(true);setError('');try{await api.save(user,property,f);setEditing(false);setTick(t=>t+1);setNotice('Justificatifs transmis. La publication attend le contrôle du dossier et de l’annonce.');}catch(e){setError(e.message);}finally{setBusy(false);}};
 const decide=async(status)=>{setBusy(true);setError('');try{await api.review(user,record.id,{p_status:status,p_checks:checks,p_evidence:evidence,p_response:response,p_until:until});setTick(t=>t+1);setNotice(status==='verified'?'Dossier validé. Vous pouvez maintenant publier l’annonce.':'Réponse enregistrée dans le compte du déposant.');}catch(e){setError(e.message);}finally{setBusy(false);}};
 const stale=record&&record.revision!==property.evidence_revision;
 return <section className="pv-panel" style={{textAlign:'left'}} aria-label="Lien avec le bien"><h3>Votre lien avec le bien</h3><p>Annonce : {property.title} · {property.country} · {property.city}</p><p className="pv-small">Pièces privées, jamais affichées dans l’annonce. Ce contrôle documentaire ne certifie pas le titre foncier et ne remplace pas les vérifications du notaire ou de l’administration.</p>
 {!loaded?<button type="button" onClick={()=>{setError('');setTick(t=>t+1);}}>Charger le dossier</button>:<>
 {record&&<p className="pv-note"><strong>{stale?'Annonce modifiée : dossier à renouveler':({en_attente:'Contrôle en cours',complement:'Compléments demandés',verified:new Date(record.valid_until)>new Date()?'Contrôle documentaire validé':'Contrôle à renouveler',suspended:'Contrôle suspendu'})[record.status]}</strong>{record.response&&<span><br/>{record.response}</span>}</p>}
 {admin?<>{!record?<p>Le déposant doit transmettre ses justificatifs avant publication.</p>:<><p><strong>Titulaire déclaré :</strong> {record.holder_name}<br/><strong>Situation :</strong> {({sole:'Titulaire unique',shared:'Propriété partagée / indivision',estate:'Succession',other:'Autre situation'})[record.situation]}<br/>{record.basis}</p><ul>{needs.map(n=>{const d=record.documents[n.code];return <li key={n.code}><strong>{n.label}</strong>{d?<><p>{d.reference} · {d.issuer} · {d.no_expiry?'Sans échéance':d.expires_on}</p><button type="button" onClick={async()=>{try{setFileUrl(await api.open(user,d.path));}catch(e){setError(e.message);}}}>Préparer l’ouverture</button></>:<p>{n.optional?'Aucun complément':'Pièce manquante'}</p>}</li>;})}</ul>{fileUrl&&<a href={fileUrl} target="_blank" rel="noopener noreferrer">Ouvrir le fichier privé</a>}<fieldset disabled={busy||stale}>{[['identity','Identité et coordonnées rapprochées des pièces'],['right','Pièce, titulaire et bien concordants ; portée du droit vérifiée'],['authority','Pouvoir de publier vérifié, y compris mandat / autres titulaires'],['risk','Incohérences, succession ou indivision examinées et résolues']].map(([k,label])=><label className="pv-check" key={k}><input type="checkbox" checked={!!checks[k]} onChange={e=>setChecks({...checks,[k]:e.target.checked})}/>{label}</label>)}<label>Sources, références et résultat du contrôle<textarea rows={4} value={evidence} maxLength={5000} onChange={e=>setEvidence(e.target.value)} placeholder="Expliquez comment le lien avec le bien et le pouvoir de publier ont été établis. Une simple copie reçue ne suffit pas."/></label><label>Échéance du contrôle (12 mois maximum)<input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label></fieldset><label>Réponse au déposant<textarea value={response} rows={3} maxLength={4000} onChange={e=>setResponse(e.target.value)}/></label><div className="pv-actions"><button type="button" disabled={busy||stale} onClick={()=>decide('verified')}>Valider le lien avec le bien</button><button type="button" disabled={busy} onClick={()=>decide('complement')}>Demander un complément</button><button type="button" disabled={busy} onClick={()=>decide('suspended')}>Suspendre</button></div><p className="pv-small">Réponse visible dans le compte. Aucun email envoyé par cette action.</p></>}</>:record&&!editing?<button type="button" onClick={()=>setEditing(true)}>Compléter ou renouveler le dossier</button>:<>
 <p>Fournissez un document permettant de rapprocher votre nom ou celui du titulaire avec ce bien : acte, attestation administrative ou autre justificatif adapté à votre situation et au pays. Son intitulé ne garantit pas qu’il autorise la vente ou la location ; Sokilé examine sa portée. Une facture seule ne prouve pas la propriété.</p>
 <p>Si vous représentez le titulaire, joignez une autorisation qui identifie le bien, le titulaire, votre nom et l’opération autorisée. En cas de succession ou de propriété partagée, indiquez les autres droits à prendre en compte.</p>
 <fieldset disabled={busy} className="pv-fields"><legend>Votre situation</legend><label>Nom du titulaire des droits *<input value={f.holder_name} maxLength={200} onChange={e=>put('holder_name',e.target.value)}/></label><label>Situation du bien<select value={f.situation} onChange={e=>put('situation',e.target.value)}><option value="sole">Titulaire unique</option><option value="shared">Propriété partagée / indivision</option><option value="estate">Succession</option><option value="other">Autre situation</option></select></label><label>Votre lien avec le bien et votre pouvoir de le proposer *<textarea rows={3} value={f.basis} maxLength={3000} onChange={e=>put('basis',e.target.value)}/></label></fieldset>
 {needs.map(n=>{const d=f.documents[n.code]||{};return <fieldset disabled={busy} className="pv-document" key={n.code}><legend>{n.label}{n.optional?' — facultatif au dépôt':' *'}</legend><label>PDF, JPG ou PNG · 5 Mo maximum<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{upload(n.code,e.target.files?.[0]);e.target.value='';}}/></label>{d.path&&<p>✓ {d.name||'Fichier ajouté'}</p>}<label>Référence du document<input value={d.reference||''} maxLength={200} onChange={e=>putDoc(n.code,{reference:e.target.value})}/></label><label>Émetteur / signataire<input value={d.issuer||''} maxLength={200} onChange={e=>putDoc(n.code,{issuer:e.target.value})}/></label><label>Date de fin de validité<input type="date" disabled={d.no_expiry} value={d.expires_on||''} onChange={e=>putDoc(n.code,{expires_on:e.target.value})}/></label><label className="pv-check"><input type="checkbox" checked={!!d.no_expiry} onChange={e=>putDoc(n.code,{no_expiry:e.target.checked,expires_on:''})}/>Le document n’indique pas d’échéance.</label></fieldset>;})}
 <p className="pv-small">Masquez les informations inutiles : coordonnées bancaires, prix d’une ancienne transaction, données de tiers sans rapport. Conservez lisibles les titulaires concernés, le bien, l’émetteur, les références et les dates. N’ajoutez pas de pièce d’identité sauf demande justifiée de Sokilé. <a href="/confidentialites.html" target="_blank" rel="noopener noreferrer">Confidentialité</a></p>
 <label className="pv-check"><input type="checkbox" checked={f.consent} disabled={busy} onChange={e=>put('consent',e.target.checked)}/>Je confirme l’exactitude des documents et mon autorisation à proposer ce bien ; j’accepte leur examen par Sokilé. *</label><button type="button" disabled={busy} className="pv-primary" onClick={save}>{busy?'Enregistrement…':'Transmettre mes justificatifs'}</button>
 </>}
 </>}{error&&<p role="alert" className="pv-error">{error}</p>}{notice&&<p role="status" className="pv-success">{notice}</p>}</section>;
}
