import {useEffect,useState} from 'react';
import {ACTIVITIES,COUNTRIES,REGULATION_VERSION,ruleFor,specialtyActivity,verificationValid,dossierError,STATE_LABELS} from './pro-regulations.mjs';
import './pro-verification.css';
const date=value=>value?new Date(value).toLocaleDateString('fr-FR',{timeZone:'UTC'}):'—';
const countryLabel=c=>c==='Congo'?'Congo-Brazzaville':c;
function Sources({rule}){return <div className="pv-sources">{rule.sources.map(s=><a key={s.url} href={s.url} target="_blank" rel="noopener noreferrer">{s.label} ↗</a>)}</div>;}
export function VerificationBadge({valid,checkedAt}){return valid?<a className="pv-badge" href="/verification-professionnels" title={`Identité et justificatifs professionnels contrôlés${checkedAt?' le '+date(checkedAt):''}. Voir la portée du contrôle.`}>✓ Professionnel vérifié</a>:null;}
export function VerificationPage(){
 const [country,setCountry]=useState('Tous'),[activity,setActivity]=useState('agence');
 const selectedRule=country==='Tous'?null:ruleFor(country,activity);
 return <article className="pv-page">
  <header className="pv-hero"><span className="pv-eyebrow">LA CONFIANCE SE CONSTRUIT</span><h1>Comment Sokilé vérifie les professionnels</h1><p>Avant de publier, chaque professionnel doit faire vérifier son identité professionnelle et les justificatifs correspondant à son activité, dans le pays concerné.</p><a href="/?tab=compte">Préparer mon dossier professionnel →</a></header>
  <section className="pv-steps" aria-label="Les étapes de vérification">{[['01','Identifier la structure','Nous rapprochons son immatriculation, son nom et le pouvoir de son représentant.'],['02','Contrôler les habilitations','Nous examinons les pièces requises, leur validité et les sources officielles ou confirmations de l’autorité compétente.'],['03','Valider avant publication','Le dossier doit être accepté par Sokilé. Un document reçu ne suffit pas pour obtenir le badge.']].map(([n,h,p])=><div key={n}><span>{n}</span><h2>{h}</h2><p>{p}</p></div>)}</section>
  <section className="pv-section"><h2>Un badge avec une portée précise</h2><VerificationBadge valid/><p>Ce badge concerne <strong>le professionnel, son activité et le pays contrôlés</strong>. Il ne certifie ni un titre foncier, ni la propriété du bien, ni la qualité des travaux ou la sécurité d’un paiement. Les annonces font également l’objet d’une modération distincte.</p><p>Les particuliers ne reçoivent pas ce badge professionnel. Ils déclarent leur rôle et transmettent un justificatif privé de leur lien avec le bien ; s’ils représentent le titulaire, ils ajoutent une autorisation. Le contrôle documentaire et la modération doivent être validés avant publication. Les exemples de démonstration restent signalés comme tels.</p><p>Le contrôle Sokilé est renouvelé au maximum tous les douze mois ; cette durée ne modifie pas celle des autorisations administratives. La vérification s’arrête plus tôt si un justificatif expire. Une suspension ou une échéance dépassée retire la visibilité des publications professionnelles concernées jusqu’à régularisation.</p></section>
  <section className="pv-section"><span className="pv-eyebrow">12 PAYS · RÈGLES PAR ACTIVITÉ</span><h2>Quels documents préparer ?</h2><p>Les pièces de base sont une preuve d’existence professionnelle et le pouvoir du représentant. Les pièces supplémentaires dépendent du pays et de l’activité.</p><div className="pv-filters"><label>Pays<select value={country} onChange={e=>setCountry(e.target.value)}><option>Tous</option>{COUNTRIES.map(c=><option value={c} key={c}>{countryLabel(c)}</option>)}</select></label><label>Activité<select value={activity} onChange={e=>setActivity(e.target.value)}>{Object.entries(ACTIVITIES).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label></div>
  <p className="pv-selection" role="status" aria-live="polite" aria-atomic="true">{country==='Tous'?`Documents pour les ${COUNTRIES.length} pays · ${ACTIVITIES[activity]}`:`Documents pour ${countryLabel(country)} · ${ACTIVITIES[activity]}`}</p>
  {selectedRule?<section className="pv-result" aria-labelledby="pv-result-title">
   <h3 id="pv-result-title">{countryLabel(country)} · {ACTIVITIES[activity]}</h3>
   <h4>Pièces à préparer pour votre dossier</h4>
   <ul className="pv-result-docs">{selectedRule.docs.map(d=><li key={d.code}><span>{d.label}</span><small>{d.required===false?'Facultatif au dépôt':d.legal?'Exigence légale documentée':'Pièce de base demandée par Sokilé'}</small></li>)}</ul>
   <div className="pv-result-review"><strong className={selectedRule.status==='confirmed'?'pv-confirmed':'pv-pending'}>{selectedRule.status==='confirmed'?'Exigences légales documentées':selectedRule.statusLabel}</strong><p>{selectedRule.summary}</p><h4>Autorité et sources</h4><p>{selectedRule.authority}</p><Sources rule={selectedRule}/>{!selectedRule.sources.length&&<p className="pv-small">Recherche juridique à compléter par Sokilé avant validation.</p>}</div>
   <p className="pv-small">Référentiel consulté le 1er octobre 2026.</p>
  </section>:
  <div className="pv-table-wrap"><table><caption>Pièces complémentaires aux justificatifs de base · référentiel consulté le 1er octobre 2026</caption><thead><tr><th>Pays</th><th>Justificatifs et contrôle</th><th>Autorité / sources</th></tr></thead><tbody>{COUNTRIES.filter(c=>country==='Tous'||country===c).map(c=>{const rule=ruleFor(c,activity);return <tr key={c}><th scope="row">{countryLabel(c)}</th><td><strong className={rule.status==='confirmed'?'pv-confirmed':'pv-pending'}>{rule.status==='confirmed'?'Exigences légales documentées':rule.statusLabel}</strong><p>{rule.summary}</p>{rule.status!=='confirmed'&&<p>Pour commencer : preuve d’existence professionnelle et pouvoir du représentant. Les éventuelles pièces légales seront précisées après examen.</p>}<ul>{rule.docs.slice(2).map(d=><li key={d.code}>{d.label}{d.required===false?' — facultatif au dépôt':''}</li>)}</ul></td><td>{rule.authority}<Sources rule={rule}/>{!rule.sources.length&&<small>Recherche juridique à compléter par Sokilé avant validation.</small>}</td></tr>;})}</tbody></table></div>}
  <p className="pv-note">Les obligations légales documentées sont distinguées des pièces demandées par Sokilé. Quand le régime nécessite un examen, vous pouvez déposer les pièces de base : Sokilé poursuit les vérifications et précise les compléments nécessaires. Aucune lettre de votre administration n’est exigée systématiquement. La publication attend la validation du dossier.</p></section>
  <section className="pv-section"><h2>Un dépôt simple et confidentiel</h2><p>Choisissez votre pays et votre activité dans votre compte ou dans le formulaire. Ajoutez les justificatifs, leur référence, leur organisme émetteur et leur échéance. Un même dossier sert à plusieurs annonces dans ce pays et pour cette activité.</p><p>Vous pouvez préparer vos annonces pendant la vérification. Elles deviennent visibles après validation du dossier professionnel puis de l’annonce. Si vous exercez dans plusieurs pays, chaque pays fait l’objet d’un dossier distinct.</p><p>Vos fichiers restent privés : seuls votre compte et l’équipe habilitée de Sokilé y ont accès. N’envoyez ni casier judiciaire, ni relevé bancaire, ni document personnel sans rapport avec le contrôle. Masquez les données inutiles en conservant les références, le titulaire, l’autorité et les dates lisibles.</p><a href="/confidentialites.html">Protection des données et durées de conservation</a></section>
  <section className="pv-contact"><h2>Un justificatif particulier ?</h2><p>Une carte d’association ou une formation privée ne remplace pas une autorisation administrative. Une immatriculation prouve l’existence d’une structure ; elle ne suffit pas à prouver son habilitation à une activité réglementée.</p><a href="mailto:contact@sokile.com">Contacter Sokilé</a></section>
 </article>;
}
export function VerificationPanel({api,user,country,activity,businessName=''}){
 if(!country||!activity)return <p className="pv-note">Sélectionnez le pays et l’activité pour afficher les justificatifs professionnels.</p>;
 return <DossierEditor key={`${user.id}:${country}:${activity}`} {...{api,user,country,activity,businessName}}/>;
}
function DossierEditor({api,user,country,activity,businessName}){
 const rule=ruleFor(country,activity);
 const [record,setRecord]=useState(null),[loading,setLoading]=useState(true),[failed,setFailed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[edit,setEdit]=useState(false),[retry,setRetry]=useState(0);
 const [f,setF]=useState({business_name:businessName||user.agency||'',representative_name:user.name||'',registration_number:'',documents:{},consent:false});
 useEffect(()=>{let active=true;setLoading(true);setFailed(false);api.load(user,`owner_id=eq.${user.id}&country=eq.${encodeURIComponent(country)}&activity=eq.${activity}`).then(rows=>{if(!active)return;const d=rows[0];setRecord(d||null);if(d)setF({...d,consent:false});}).catch(()=>{if(active){setFailed(true);setError('Le dossier ne peut pas être chargé. Réessayez avant de continuer.');}}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user.token,retry]);
 const set=(key,value)=>setF(old=>({...old,[key]:value}));
 const setDoc=(code,patch)=>setF(old=>({...old,documents:{...old.documents,[code]:{...old.documents?.[code],...patch}}}));
 const upload=async(code,file)=>{if(!file||busy)return;setBusy(true);setError('');try{setDoc(code,await api.upload(user,file));}catch(e){setError(e.message);}finally{setBusy(false);}};
 const save=async()=>{if(busy)return;const invalid=dossierError(f,rule);if(invalid){setError(invalid);return;}setBusy(true);setError('');try{const [d]=await api.save(user,{...f,id:record?.id,country,activity,rule_version:REGULATION_VERSION});setRecord(d);setF({...d,consent:false});setEdit(false);setNotice('Dossier transmis. La décision et les éventuelles pièces à compléter seront affichées ici.');}catch(e){setError(e.message);}finally{setBusy(false);}};
 if(!rule)return <p className="pv-error">Ce pays ou cette activité n’est pas pris en charge.</p>;
 const valid=verificationValid(record);
 return <section className="pv-panel" aria-label={`Justificatifs — ${countryLabel(country)}`}>
  <div className="pv-panel-title"><div><span className="pv-eyebrow">VOTRE DOSSIER PROFESSIONNEL</span><h3>{countryLabel(country)} · {ACTIVITIES[activity]}</h3></div>{valid&&<VerificationBadge valid checkedAt={record.verified_at}/>}</div>
  <p className="pv-small">Un dossier réutilisable pour vos publications dans ce pays. <a href="/verification-professionnels" target="_blank" rel="noopener noreferrer">Comprendre les vérifications ↗</a></p>
  {loading?<p role="status">Chargement de votre dossier…</p>:failed?<button type="button" onClick={()=>{setError('');setRetry(n=>n+1);}}>Réessayer</button>:<>
   {record&&<div className="pv-note"><strong>{record.status==='verified'&&!valid?'Vérification à renouveler':STATE_LABELS[record.status]}</strong>{record.valid_until&&<span> · Échéance : {date(record.valid_until)}</span>}{record.response&&<p>Réponse de Sokilé : {record.response}</p>}</div>}
   {record&&!edit?<><p>{valid?'Votre dossier peut servir à la validation de vos publications pour ce pays et cette activité.':'Vos annonces peuvent être préparées ; leur publication reste suspendue à la validation de ce dossier.'}</p><button type="button" onClick={()=>setEdit(true)}>Compléter ou renouveler mes justificatifs</button></>:<>
    {valid&&<p className="pv-note">L’envoi d’une modification relancera la vérification et suspendra les publications concernées jusqu’à la nouvelle validation.</p>}
    <p>{rule.summary}</p><Sources rule={rule}/>
    <fieldset className="pv-fields" disabled={busy}><legend>Structure et représentant</legend>{[['business_name','Nom légal de la structure'],['representative_name','Nom du représentant'],['registration_number','Référence d’immatriculation / d’ordre']].map(([k,label])=><label key={k}>{label} *<input value={f[k]||''} maxLength={200} onChange={e=>set(k,e.target.value)}/></label>)}</fieldset>
    <div className="pv-docs">{rule.docs.map(need=>{const d=f.documents?.[need.code]||{};return <fieldset disabled={busy} key={need.code} className="pv-document"><legend>{need.label}{need.required===false?' — facultatif au dépôt':' *'}</legend><small>{need.legal?'Justificatif lié à une exigence documentée.':'Pièce demandée par Sokilé pour instruire le dossier.'}</small><label>Fichier privé · PDF, JPG ou PNG · 5 Mo maximum<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>{upload(need.code,e.target.files?.[0]);e.target.value='';}}/></label>{d.path&&<p className="pv-file">✓ Fichier ajouté : {d.name||'Justificatif'}</p>}<div className="pv-fields"><label>Numéro / référence *<input value={d.reference||''} maxLength={200} onChange={e=>setDoc(need.code,{reference:e.target.value})}/></label><label>Organisme émetteur *<input value={d.issuer||''} maxLength={200} onChange={e=>setDoc(need.code,{issuer:e.target.value})}/></label><label>Date de fin de validité<input type="date" disabled={d.no_expiry} value={d.expires_on||''} onChange={e=>setDoc(need.code,{expires_on:e.target.value})}/></label></div><label className="pv-check"><input type="checkbox" checked={!!d.no_expiry} onChange={e=>setDoc(need.code,{no_expiry:e.target.checked,expires_on:e.target.checked?'':d.expires_on})}/>Le document ne mentionne pas de date d’expiration.</label></fieldset>;})}</div>
    <p className="pv-small">Fichiers privés, réservés à votre compte et à l’équipe habilitée de Sokilé. Masquez les informations personnelles inutiles. <a href="/confidentialites.html" target="_blank" rel="noopener noreferrer">Confidentialité</a></p>
    <label className="pv-check"><input type="checkbox" disabled={busy} checked={f.consent} onChange={e=>set('consent',e.target.checked)}/>Je confirme l’exactitude des pièces, mon pouvoir de représentation et accepte leur contrôle par Sokilé. *</label>
    <button type="button" className="pv-primary" disabled={busy} onClick={save}>{busy?'Enregistrement…':'Envoyer mes justificatifs pour vérification'}</button>
   </>}
  </>}
  {error&&<p className="pv-error" role="alert">{error}</p>}{notice&&<p className="pv-success" role="status">{notice}</p>}
 </section>;
}
export function VerificationWorkspace({api,user}){
 const [country,setCountry]=useState('Cameroun'),[activity,setActivity]=useState('agence');
 return <details className="pv-workspace"><summary>Mes justificatifs professionnels</summary><p>Choisissez chaque pays et chaque activité pour lesquels vous souhaitez publier.</p><div className="pv-filters"><label>Pays<select value={country} onChange={e=>setCountry(e.target.value)}>{COUNTRIES.map(c=><option key={c} value={c}>{countryLabel(c)}</option>)}</select></label><label>Activité<select value={activity} onChange={e=>setActivity(e.target.value)}>{Object.entries(ACTIVITIES).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label></div><VerificationPanel {...{api,user,country,activity}}/></details>;
}
export function DirectoryVerifications({api,user,countries,specialty,businessName}){return <>{countries.map(country=><VerificationPanel key={country} {...{api,user,country,businessName}} activity={specialtyActivity(specialty)}/>)}</>;}
export function VerificationAdmin({api,user}){
 const [rows,setRows]=useState([]),[selected,setSelected]=useState(null),[status,setStatus]=useState('en_attente'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[tick,setTick]=useState(0);
 useEffect(()=>{let active=true;setLoading(true);setError('');api.load(user,`status=eq.${status}&order=submitted_at.desc&limit=100`).then(d=>{if(active)setRows(d);}).catch(e=>{if(active)setError(e.message);}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[user.token,status,tick]);
 return <section className="pv-admin"><h2>Vérifier les professionnels</h2><p>Contrôlez les justificatifs auprès de sources indépendantes avant d’accorder le badge. La validation d’un dossier ne publie pas automatiquement les annonces.</p><div className="pv-actions">{Object.entries(STATE_LABELS).map(([k,v])=><button type="button" key={k} aria-pressed={status===k} onClick={()=>setStatus(k)}>{v}</button>)}<button type="button" onClick={()=>setTick(n=>n+1)}>Actualiser</button></div>{loading?<p role="status">Chargement…</p>:rows.length?rows.map(d=><button type="button" className="pv-admin-row" key={d.id} onClick={()=>setSelected(d)}><strong>{d.business_name}</strong><span>{countryLabel(d.country)} · {ACTIVITIES[d.activity]} · {date(d.submitted_at)}</span>{d.valid_until&&<span>Échéance : {date(d.valid_until)}</span>}</button>):<p>Aucun dossier dans cette catégorie.</p>}{error&&<p role="alert" className="pv-error">{error}</p>}{selected&&<AdminReview key={selected.id} {...{api,user}} record={selected} onClose={()=>setSelected(null)} onSaved={()=>{setSelected(null);setTick(n=>n+1);}}/>}</section>;
}
function AdminReview({api,user,record,onClose,onSaved}){
 const rule=ruleFor(record.country,record.activity);
 const [evidence,setEvidence]=useState(''),[response,setResponse]=useState(''),[until,setUntil]=useState(new Date(Date.now()+180*86400000).toISOString().slice(0,10)),[checks,setChecks]=useState({}),[busy,setBusy]=useState(false),[error,setError]=useState(''),[fileUrl,setFileUrl]=useState('');
 useEffect(()=>()=>{if(fileUrl)URL.revokeObjectURL(fileUrl);},[fileUrl]);
 const decide=async status=>{setError('');setBusy(true);try{await api.review(user,record.id,{p_status:status,p_evidence:evidence,p_response:response,p_valid_until:until,p_checks:checks});onSaved();}catch(e){setError(e.message);}finally{setBusy(false);}};
 return <div className="pv-overlay"><section role="dialog" aria-modal="true" aria-label="Contrôle du dossier professionnel" className="pv-review"><header><h2>{record.business_name}</h2><button type="button" disabled={busy} onClick={onClose} aria-label="Fermer le dossier">✕</button></header><p>{countryLabel(record.country)} · {ACTIVITIES[record.activity]}<br/>Représentant : {record.representative_name}<br/>Immatriculation : {record.registration_number}</p><p className="pv-note">{rule.summary}</p><Sources rule={rule}/><ul className="pv-review-docs">{rule.docs.map(need=>{const d=record.documents?.[need.code];return <li key={need.code}><strong>{need.label}</strong>{d?<><p>{d.reference} · {d.issuer}<br/>{d.no_expiry?'Sans échéance indiquée':`Échéance : ${date(d.expires_on)}`}</p><button type="button" onClick={async()=>{setError('');try{setFileUrl(await api.open(user,d.path));}catch(e){setError(e.message);}}}>Préparer l’ouverture du justificatif</button></>:<p className={need.required===false?"pv-small":"pv-error"}>{need.required===false?"Aucun complément déposé":"Pièce manquante"}</p>}</li>;})}</ul>{fileUrl&&<a href={fileUrl} target="_blank" rel="noopener noreferrer" className="pv-primary">Ouvrir le justificatif privé ↗</a>}
 <fieldset disabled={busy} className="pv-review-fields"><legend>Trace du contrôle</legend>{[['identity','Structure et représentant concordants'],['documents','Pièces authentifiées, activité et validité contrôlées'],['regime','Régime applicable établi ; autorisations nécessaires vérifiées ou absence d’exigence justifiée']].map(([k,v])=><label className="pv-check" key={k}><input type="checkbox" checked={!!checks[k]} onChange={e=>setChecks({...checks,[k]:e.target.checked})}/>{v}</label>)}<label>Sources et résultat du contrôle *<textarea value={evidence} onChange={e=>setEvidence(e.target.value)} rows={4} maxLength={5000} placeholder="URL du registre officiel, numéro vérifié, date et résultat ; ou autorité contactée, référence de sa réponse et conclusion sur les autorisations applicables."/></label><label>Échéance de la vérification (12 mois maximum)<input type="date" value={until} onChange={e=>setUntil(e.target.value)}/></label><label>Réponse au professionnel (obligatoire pour compléter ou suspendre)<textarea value={response} onChange={e=>setResponse(e.target.value)} maxLength={4000} rows={3}/></label></fieldset>
 <div className="pv-actions"><button type="button" className="pv-primary" disabled={busy} onClick={()=>decide('verified')}>Valider le dossier professionnel</button><button type="button" disabled={busy} onClick={()=>decide('complement')}>Demander des pièces</button><button type="button" disabled={busy} onClick={()=>decide('suspended')}>Suspendre la vérification</button></div>{error&&<p className="pv-error" role="alert">{error}</p>}<p className="pv-small">La réponse sera visible dans le compte. Aucun email n’est envoyé par cette action.</p></section></div>;
}
export function VerificationAdminHint({country,activity}){return <p className="pv-note">Avant de publier : validez le dossier professionnel pour {countryLabel(country)} ({ACTIVITIES[activity]||'activité déclarée'}) dans « Vérifications pro ». Le serveur contrôle sa validité.</p>;}
