import {useEffect,useRef,useState} from 'react';
import {REQUEST_COUNTRIES,REQUEST_NATURES,REQUEST_DRAFT,requestFilters,requestSummary,requestBudget,requestMatches} from './search-requests.mjs';
import './search-requests.css';
const blank={country:'',city:'',transaction:'location',nature:'appartement',budget:'',rooms:''};
function draft(){try{return {...blank,...JSON.parse(sessionStorage.getItem(REQUEST_DRAFT)||'{}')}}catch{return blank}}
const errorText=r=>r?.motif||'Impossible de terminer cette action. Réessayez.';
const date=v=>new Date(v).toLocaleDateString('fr-FR');
export function SearchRequestBanner(){return <aside className="sr-banner"><div><span>Votre projet immobilier</span><h2>Vous ne trouvez pas encore votre bien ?</h2><p>Décrivez votre recherche. Avec votre accord, les professionnels vérifiés du pays pourront vous proposer leurs annonces.</p></div><a className="sr-button" href="/recherche">Décrire ma recherche</a></aside>}
export function SearchRequestPage({user,rpc,onLogin,onSaved}){
 const [form,setForm]=useState(draft),[share,setShare]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),[saved,setSaved]=useState(null);const lock=useRef(false),identity=useRef(user?.id);identity.current=user?.id;
 const change=(k,v)=>{const next={...form,[k]:v};setForm(next);setError('');try{sessionStorage.setItem(REQUEST_DRAFT,JSON.stringify(next))}catch{}};
 const submit=async e=>{e.preventDefault();if(lock.current)return;setError('');let filters;try{filters=requestFilters(form)}catch(e){setError(e.message);return}if(!user){onLogin();return}const owner=user.id;lock.current=true;setBusy(true);try{const r=await rpc('sokile_create_search_request',{p_filters:filters,p_share:share},user.token);if(!r.ok)throw Error(errorText(r));if(identity.current!==owner)return;setSaved(r.data);try{sessionStorage.removeItem(REQUEST_DRAFT)}catch{}onSaved?.();}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}};
 return <section className="sr-page"><a href="/?tab=biens" className="sr-back">Retour aux annonces</a><span className="sr-eyebrow">SOKILÉ · VOTRE RECHERCHE</span><h1>{saved?'Votre recherche est enregistrée':'Le bon bien commence par votre recherche.'}</h1>{saved?<div className="sr-card" role="status"><h2>{requestSummary(saved.filters)}</h2><p>{saved.shared_with_pros?'Les agences et promoteurs vérifiés pour ce pays peuvent maintenant consulter vos critères et proposer un bien.':'Votre recherche reste privée : vous recevrez les nouvelles annonces correspondant à vos critères.'}</p><p>Les notifications sont envoyées à <strong>{saved.email}</strong>. Vos coordonnées ne sont pas communiquées aux professionnels. Vous choisissez ensuite qui contacter.</p><p>Valable jusqu’au {date(saved.expires_at)}. Vous pouvez arrêter le partage ou annuler la recherche dans votre compte. Une proposition n’est pas garantie.</p><a className="sr-button" href="/?tab=compte">Gérer ma recherche</a></div>:<><p className="sr-intro">Décrivez le bien souhaité et recevez les annonces correspondantes par email. Le partage avec des professionnels est facultatif.</p><form className="sr-card" onSubmit={submit}><div className="sr-grid">
 <label>Pays<select required value={form.country} onChange={e=>change('country',e.target.value)}><option value="">Choisir un pays</option>{REQUEST_COUNTRIES.map(c=><option key={c}>{c}</option>)}</select></label>
 <label>Ville<input required maxLength={80} placeholder="Ex. Douala" value={form.city} onChange={e=>change('city',e.target.value)}/></label>
 <label>Votre projet<select value={form.transaction} onChange={e=>change('transaction',e.target.value)}><option value="location">Louer</option><option value="vente">Acheter</option></select></label>
 <label>Type de bien<select value={form.nature} onChange={e=>change('nature',e.target.value)}>{Object.entries(REQUEST_NATURES).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>
 <label>Budget maximum en FCFA{form.transaction==='location'?' / mois':''}<input required type="number" inputMode="numeric" min="1000" max="1000000000000" step="1" value={form.budget} onChange={e=>change('budget',e.target.value)}/></label>
 <label>Pièces minimum (facultatif)<select value={form.rooms} onChange={e=>change('rooms',e.target.value)}><option value="">Sans préférence</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n}{n===5?' ou plus':''}</option>)}</select></label>
 </div><label className="sr-consent"><input type="checkbox" checked={share} onChange={e=>setShare(e.target.checked)}/><span>J’accepte de partager mes critères de recherche avec les agences et promoteurs dont le dossier est vérifié par Sokilé pour ce pays, afin qu’ils puissent proposer leurs annonces. Mes coordonnées restent privées. Je peux retirer cet accord dans mon compte.</span></label>
 <p className="sr-note">Recherche valable un an, annulable à tout moment. Aucun abonnement publicitaire. La disponibilité d’un bien et les délais de réponse ne sont pas garantis. <a href="/confidentialites.html" target="_blank" rel="noopener noreferrer">Confidentialité</a></p>
 {user?<p>Email de réception : <strong>{user.email}</strong></p>:<p>Un compte gratuit avec une adresse email confirmée est nécessaire pour enregistrer et gérer votre recherche. Vos critères seront conservés pendant la connexion sur cet onglet.</p>}
 {error&&<p role="alert" className="sr-error">{error}</p>}<button disabled={busy} className="sr-button" type="submit">{busy?'Enregistrement…':user?'Enregistrer ma recherche':'Continuer avec mon compte'}</button>
 </form></>}</section>
}
export function ProfessionalSearchRequests({user,rpc,load,onListing,refreshKey}){
 const [rows,setRows]=useState([]),[properties,setProperties]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[notice,setNotice]=useState(''),[selected,setSelected]=useState({}),[busy,setBusy]=useState(false),[retry,setRetry]=useState(0);const lock=useRef(false);
 useEffect(()=>{let live=true;setLoading(true);setRows([]);setProperties([]);setError('');(async()=>{const [r,p]=await Promise.all([rpc('sokile_list_search_requests',{},user.token),load('properties',`select=id,title,country,city,nature,transaction,price_eur,rooms&owner_id=eq.${encodeURIComponent(user.id)}&status=eq.validee&active=eq.true&expires_at=gt.${encodeURIComponent(new Date().toISOString())}`,user.token)]);if(!r.ok||!p.ok)throw Error('Impossible de charger les recherches.');if(live){setRows(r.data||[]);setProperties(p.data||[])}})().catch(e=>{if(live)setError(e.message)}).finally(()=>{if(live)setLoading(false)});return()=>{live=false}},[user.id,user.token,retry,refreshKey,rpc,load]);
 const propose=async row=>{if(lock.current||!selected[row.id])return;lock.current=true;setBusy(true);setError('');setNotice('');try{const r=await rpc('sokile_propose_search_property',{p_request:row.id,p_property:Number(selected[row.id])},user.token);if(!r.ok||r.data!==true)throw Error(errorText(r));setNotice('Proposition enregistrée. Une notification sera envoyée au demandeur si la recherche et l’annonce restent actives.');setRetry(x=>x+1)}catch(e){setError(e.message)}finally{lock.current=false;setBusy(false)}};
 return <section className="sr-pro sr-card"><h2>Recherches de clients</h2><p>Les demandes partagées pour les pays où votre dossier d’agence ou de promoteur est vérifié. Les coordonnées des demandeurs restent privées.</p>{loading&&<p role="status">Chargement…</p>}{error&&<p className="sr-error" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{!loading&&!error&&!rows.length&&<p>Aucune recherche accessible pour le moment. Votre dossier doit être vérifié et en cours de validité pour le pays concerné.</p>}
 {rows.map(row=>{const matches=properties.filter(p=>requestMatches(row.filters,p)&&!row.proposed_property_ids.some(id=>String(id)===String(p.id)));return <article key={row.id}><h3>{requestSummary(row.filters)}</h3><p>{requestBudget(row.filters)}</p><p className="sr-note">Déposée le {date(row.created_at)} · expire le {date(row.expires_at)}</p>{row.proposed_property_ids.length>0&&<p>Une annonce a déjà été proposée pour cette recherche.</p>}{matches.length?<div className="sr-response"><label>Votre annonce correspondante<select value={selected[row.id]||''} onChange={e=>setSelected(s=>({...s,[row.id]:e.target.value}))}><option value="">Choisir une annonce publiée</option>{matches.map(p=><option key={p.id} value={p.id}>{p.title}</option>)}</select></label><button className="sr-button" disabled={busy||!selected[row.id]} onClick={()=>propose(row)}>Proposer ce bien</button></div>:<p>Aucune de vos annonces publiées ne correspond actuellement. Vous pouvez déposer un bien adapté ; sa publication reste soumise à validation.</p>}<button className="sr-secondary" onClick={onListing}>Publier un bien</button></article>})}<button className="sr-secondary" disabled={loading||busy} onClick={()=>setRetry(x=>x+1)}>Actualiser les recherches</button></section>
}
